import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { DataProvider } from "./context/DataContext";
import AuthGuard from "./_Componants/AuthGuard";
import SecurityProvider from "./_Componants/SecurityProvider";
import GlobalLoader from "./_Componants/GlobalLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <DataProvider>
            <GlobalLoader />
            <SecurityProvider>
              <AuthGuard>{children}</AuthGuard>
            </SecurityProvider>
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
